### ISSUE TITLE
Instructions for Docker Contianer and Python Version Management in Sagemaker

### ISSUE THREAD

**Issue by towardsuffering** [aws-samples/algorithmic-trading#11]
I am going through the repo and on the SMA strategy I am getting error when trying to run **Step 4) Backtest locally** It seems we need to have a docker container running locally for this to work? There's no instructuons so hard to tell. Also, I am using Sagemaker kernel _conda_mxnet_latest_p37_ and for some reason getting an error saying i need to update from 3.6 to 3.7. I checked in the terminal and both pip and python versions good... pip 22.0.4 from /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pip (python 3.7), Python 3.7.12

**Comment by towardsuffering** [comment]
<img width="672" alt="Screenshot 2022-05-09 145704" src="https://user-images.githubusercontent.com/46471922/167487593-6cfb655e-7d43-489f-8498-b492dcf6d377.png">

**Comment by osteffmann** [comment]
This has been fixed in the dockerfile.
